### ISSUE TITLE
Cannot find module 'rx'

### ISSUE THREAD

**Issue by blitzvb** [jims/atom-stingray#51]
I installed npn and rx globally but still got this error:

`error: Cannot find module 'rx'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\vincent\AppData\Local\atom\app-1.3.2\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\vincent\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:/Users/vincent/.atom/packages/atom-stingray-master/lib/stingray/toolchain.js:5:30)
    at Module._compile (C:\Users\vincent\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\vincent\AppData\Local\atom\app-1.3.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\vincent\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\vincent\.atom\packages\atom-stingray-master\lib\main.js:21:26)
    at Module._compile (C:\Users\vincent\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\vincent\AppData\Local\atom\app-1.3.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\vincent\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\vincent\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:663:34)
    at C:\Users\vincent\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:115:28
    at Package.module.exports.Package.measure (C:\Users\vincent\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\vincent\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\vincent\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package-manager.js:438:14)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\vincent\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package-manager.js:390:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (C:\Users\vincent\AppData\Local\atom\app-1.3.2\resources\app.asar\src\atom-environment.js:682:21)
    at module.exports (C:\Users\vincent\AppData\Local\atom\app-1.3.2\resources\app.asar\src\initialize-application-window.js:28:10)
    at setupWindow (file:///C:/Users/vincent/AppData/Local/atom/app-1.3.2/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///C:/Users/vincent/AppData/Local/atom/app-1.3.2/resources/app.asar/static/index.js:41:9)`

**Comment by jims** [comment]
This is the same as #52
